### PR TITLE
Update GitHub Apps URL

### PR DESCRIPTION
**Pull request by dvdliao**

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/policy-bot](https://github.com/palantir/policy-bot), @dvdliao! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by bluekeyes** [comment]
Thanks for making this change. Do you happen to know if this new URL is also used in GitHub Enterprise 2.16.x? I just checked and 2.15.4 at least is still using the `github-apps` version.

**Comment by dvdliao** [comment]
Hm, I'm not sure about that. This is the URL for apps on normal GitHub (cloud hosted).

**Comment by bluekeyes** [comment]
We just started testing out the GitHub Enterprise 2.16 upgrade and it appears to use the old `github-apps` path. I think we'll need to find a way to switch this path based on the configured host.

**Comment by dvdliao** [comment]
Right, probably just a conditional that checks if url is `https://github.com`

**Review by bluekeyes — APPROVED** [review]
Thanks!

**Pull request merged**
